### ISSUE TITLE
Segments are not being counted since april update.

### ISSUE THREAD

**Issue by LordTreyBennett** [MarianArlt/sheolhelper#2]
Segments just sit at 0 on the counter  the whole run.

**Comment by MarianArlt** [comment]
Thank you for the report. I was aware of this but didn't comment. This happened to coincide with the v2 update. So I have made the release available now after thourough testing for several weeks/runs. This is fixed with https://github.com/MarianArlt/sheolhelper/commit/bc4a30887d50652204fbaa054621712b0a10ef96. You can simply grab the latest release by clicking [here](https://github.com/MarianArlt/sheolhelper/releases/latest/download/sheolhelper.zip).

**Comment by LordTreyBennett** [comment]
Thanks for getting the update out to us. Your plug in is the best thing to happen to odyssey from the community. Thanks so much for it.

D. "Trey" Bennett

***@***.***
***@***.***
225.270.0209
________________________________
